// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Bounty struct {
	ID     int    `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	UserID int    `json:"userId"`
	User   *User  `json:"user"`
}

type BountyResponse struct {
	Message string    `json:"message"`
	Status  int       `json:"status"`
	Data    []*Bounty `json:"data"`
}

type DefaultResponse struct {
	Message string  `json:"message"`
	Status  int     `json:"status"`
	Data    *string `json:"data"`
}

type NewBounty struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type NewUser struct {
	Username  string  `json:"username"`
	DiscordID *string `json:"discordId"`
}

type User struct {
	ID        int     `json:"id"`
	Username  string  `json:"username"`
	DiscordID *string `json:"discordId"`
}

type UserResponse struct {
	Message string  `json:"message"`
	Status  int     `json:"status"`
	Data    []*User `json:"data"`
}
